### PR TITLE
Data: Hemang Yadav & ZemPosts

### PR DESCRIPTION
**Pull request by Zemerik**
## Changes:

- Added my Profile in `index.html`
- Added my Project in `projects.html`

Thanks for Reviewing

### CODE REVIEW

**Comment by Gyanthakur** [comment]
> ## Changes:
> * Added my Profile in `index.html`
> * Added my Project in `projects.html`
> 
> Thanks for Reviewing

you are not following my account

**Comment by Zemerik** [comment]
Followed! Now Merge?

**Review by Gyanthakur — APPROVED** [review]

**Comment by Zemerik** [comment]
Can you please add the Hacktoberfest label?

**Comment by Zemerik** [comment]
@Gyanthakur Can you please add the Hacktoberfest label?

**Pull request merged**
