### PR TITLE
header redesigned

### PR DESCRIPTION
**Pull request by chaanakyaaM**
## Description

I have redesigned the header and added converted the buttons/links into navbar

image
image

Fixes: #236 

Use [x] to represent a checked (ticked) box.✅
Use [ ] to represent an unchecked box.❌

## Type of Change

- [ ] Profile Added
- [ ] Project Added
- [ ] Bug fix
- [x] New feature
- [ ] Documentation update
- [ ] Other (please specify):

## Checklist

- [x] I have performed a self-review of my code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation (if applicable).
- [x] My changes generate no new warnings.
- [x] I have added tests to cover my changes (if applicable).
- [x] All new and existing tests pass.

## Additional Notes

Please add any other information that is relevant to this pull request, including potential risks, alternative solutions considered, or future improvements.

### CODE REVIEW

**Comment by Gyanthakur** [comment]
> ## Description
> I have redesigned the header and added converted the buttons/links into navbar
> 
> image image
> 
> Fixes: #236
> 
> Use [x] to represent a checked (ticked) box.✅ Use [ ] to represent an unchecked box.❌
> 
> ## Type of Change
> * [ ]  Profile Added
> * [ ]  Project Added
> * [ ]  Bug fix
> * [x]  New feature
> * [ ]  Documentation update
> * [ ]  Other (please specify):
> 
> ## Checklist
> * [x]  I have performed a self-review of my code.
> * [x]  I have commented my code, particularly in hard-to-understand areas.
> * [x]  I have made corresponding changes to the documentation (if applicable).
> * [x]  My changes generate no new warnings.
> * [x]  I have added tests to cover my changes (if applicable).
> * [x]  All new and existing tests pass.
> 
> ## Additional Notes
> Please add any other information that is relevant to this pull request, including potential risks, alternative solutions considered, or future improvements.

change header in all sections about and contact page also

**Comment by chaanakyaaM** [comment]
Done

**Comment by Gyanthakur** [comment]
> Done
image
[Dev Profiles
 fix it in center of the left
 it having in left that good but do it in the center of the left, I think are you understand
image

like that 
image



> Done

Dev Profiles: fix it in the center of the left
it having in left that's good but i want it is in center like 
image

**Comment by Gyanthakur** [comment]
> > Done
> > image

> > Done
> 
> Dev Profiles: fix it in the center of the left it having in left that's good but i want it is in center like image

**Review by Gyanthakur — APPROVED** [review]

**Comment by chaanakyaaM** [comment]
> > > Done
> > > image
> 
> > > Done
> > 
> > 
> > Dev Profiles: fix it in the center of the left it having in left that's good but i want it is in center like image


sorry but i cant see the image
image

**Pull request merged**
